[[Messages]]
Code = "last_date_pay_bill"
Variables = {date="datetime"}
[Messages.Templates]
english = "The last date for paying bills is {date}."
arabic = "Ø¢Ø®Ø± Ø£Ø¬Ù„ Ù„ØªØ³ØªØ¯ÙŠØ¯ Ø§Ù„ÙÙˆØ§ØªÙŠØ± Ù‡Ùˆ {date}"

# error handling ğŸ˜º
[[Messages]]
Code = "err_user_access_denied"
Status = "danger" # optional
[Messages.Templates]
english = "Incorrect Username or Password! Try again."
arabic = "Ø¥Ø³Ù… Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù… Ø£Ùˆ ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ± ØºÙŠØ± ØµØ­ÙŠØ­Ø©! Ø­Ø§ÙˆÙ„ Ù…Ù† Ø¬Ø¯ÙŠØ¯."

# error handling ğŸ˜º
[[Messages]]
Code = "error_stock_limit_exceeded"
Status = "warning" # optional
Variables = {name="string", quantity="int"}
[Messages.Templates]
english = "Stock limit exceeded! Only {quantity} left in stock {name}."
arabic = "ØªÙ… ØªØ¬Ø§ÙˆØ² Ø­Ø¯ Ø§Ù„Ù…Ø®Ø²ÙˆÙ†! Ù„Ù… ÙŠØªØ¨Ù‚Ù‰ Ø³ÙˆÙ‰ {quantity} Ù…Ù† Ù…Ø®Ø²ÙˆÙ† {name}."
